### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by knopp** [seivan/swipe-to-navigate#1]
Hi,

I get this extension during startup on both latest vscode and vscode insiders:

```
The factory method of "swipe-to-navigate/swipe-to-navigate" has thrown an exception
{ ReferenceError: resultOpenFirstWindow is not defined
    at Object.<anonymous> (/Users/Matej/Library/Application Support/Code/User/globalStorage/seivan.swipe-to-navigate/patches/swipe-to-navigate.js:86:5)
    at Function.t._safeInvokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:20:548)
    at Function.t._invokeFactory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:20:795)
    at t.complete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:21:10)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:490)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:730)
    at s._resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:41)
    at s.defineModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:25:184)
    at s._onLoad (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:26:837)
    at Object.callback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:29:272)
    at e.triggerCallback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:813)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:616
    at t._createAndEvalScript (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:17:116)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:639
    at u (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:18:560)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:18:757
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  phase: 'factory',
  moduleId: 'swipe-to-navigate/swipe-to-navigate' }
```

**Comment by seivan** [comment]
@knopp Ah, thanks a bunch. Gah, maybe the patches themselves should also be written in TS and compiled before publishing.

**Comment by seivan** [comment]
`1.0.1` fixes this :)
